# Star Classification DNN (6 Class Classification)

## // Required Modules

In [16]:
import matplotlib.pyplot as plot
import numpy
import pandas
from sklearn import preprocessing, model_selection
import tensorflow as tflow
from tensorflow import keras

## // Importing dataset of stars

In [17]:
dataset = pandas.read_csv('./6 class csv.csv')

## // Upper part of dataset

In [18]:
dataset.head()

Temperature (K)  Luminosity(L/Lo)  Radius(R/Ro)  Absolute magnitude(Mv)  \
0             3068          0.002400        0.1700                   16.12   
1             3042          0.000500        0.1542                   16.60   
2             2600          0.000300        0.1020                   18.70   
3             2800          0.000200        0.1600                   16.65   
4             1939          0.000138        0.1030                   20.06   

   Star type Star color Spectral Class  
0          0        Red              M  
1          0        Red              M  
2          0        Red              M  
3          0        Red              M  
4          0        Red              M

## // Checking For NULL Values

Since value output is 'False' no need to take preprocessing actions.
If there are NULL values, need to perform removel of rows or replace with another values.

In [19]:
dataset.isnull().values.any()

False

## // Checking Stats about dataset

In [20]:
# Stellar classification:
# Type 0 represents Brown Dwarf,
# Type 1 represents Red Dwarf,
# Type 2 represents White Dwarf,
# Type 3 represents Main-Sequence,
# Type 4 represents Supergiant,
# Type 5 represents Hypergiant.

In [21]:
brown_dwarfs = len(dataset.loc[dataset['Star type'] == 0])
red_dwarfs= len(dataset.loc[dataset['Star type'] == 1])
white_dwarfs = len(dataset.loc[dataset['Star type'] == 2])
main_sequences = len(dataset.loc[dataset['Star type'] == 3])
supergiants = len(dataset.loc[dataset['Star type'] == 4])
hypergiants = len(dataset.loc[dataset['Star type'] == 5])

print("Brown dwarf          =",brown_dwarfs)
print("Red dwarf            =",red_dwarfs)
print("White Dwarf          =",white_dwarfs)
print("Main Sequence        =",main_sequences)
print("Supergiant           =",supergiants)
print("Hypergiant           =",hypergiants) 
print("Dataset total stars  =",len(dataset))

Brown dwarf          = 40
Red dwarf            = 40
White Dwarf          = 40
Main Sequence        = 40
Supergiant           = 40
Hypergiant           = 40
Dataset total stars  = 240


## // Converting Data into Numpy Arrays

Data preparation. Removing any irrelevant features from the dataset.

In [22]:
x_axis = numpy.array(dataset.drop(['Star type', 'Star color','Spectral Class'], axis=1))   # x = Temperature, Luminosity, Radius, Absolute magnitude
y_axis = numpy.array(dataset['Star type'], dtype ='float')                                 # y = star type
y_axis.shape = (len(y_axis),1)                                                             # Column -> Column vector

## // Splitting Data into Training + Testing Data

In [23]:
x_trainset ,x_testset , y_trainset, y_testset = model_selection.train_test_split(x_axis,y_axis, test_size = 0.3)    

#Splits data into 70:30 ratio
#70% for training , 30% for testing

## // Scaling data for better modelling
Preprocessing Technique : Data Transformation (Scalling)
scale the features to have zero mean and unit variance. (each feature will have a mean of 0 and a standard deviation of 1.)

Feature normalization (Z-score normalization)

In [24]:
x_train_scaled = preprocessing.scale(x_trainset)
y_train_scaled = y_trainset

x_test_scaled = preprocessing.scale(x_testset)
y_test_scaled = y_testset

## // Using DNN Model for Training Data

#initiating Sequential Neural Network

#adding 1st neural layer with 200 perceptrons

#adding 2nd neural layer with 300 perceptrons

#adding 3rd neural layer with 6 perceptrons for 6 classes to be classified.

Rectified Linear Unit (ReLU) is used for hidden layers because it shown to perform well in many deep learning applications. Sigmoid activation function is commonly used for binary classification problems, where the output is either 0 or 1. However, it may not be the best choice for multi-class classification problems, as it may have difficulty in distinguishing between multiple classes.

As the output layer activation function, softmax activation function is commonly used for multi-class classification problems because it outputs a probability distribution over the classes, where the sum of the probabilities equals one. This is particularly useful when we want to predict the probability of an input belonging to each class, as it allows us to choose the class with the highest probability as the predicted output.
If we want to predict binary outputs or regression values, then other activation functions like sigmoid or linear may be more appropriate.

Adam optimization is a stochastic (probabilistic) gradient descent method. It is a variant of the gradient descent algorithm that is designed to handle large datasets efficiently by updating the model parameters (weights and biases) incrementally on a subset of the training data, instead of the whole dataset at once.

Then the loss function. That will be used to calculate the error between the predicted and actual output during training. 'SCC' is commonly used loss function for multi-class classification problems where the target variable is integers representing the class labels. (1, 2, 3, 4, 5, 6)


In [25]:
new_model = keras.models.Sequential(
    [
        keras.layers.Dense(200,activation = tflow.nn.relu),
        keras.layers.Dense(300,activation = tflow.nn.relu),
        keras.layers.Dense(6,activation = tflow.nn.softmax)
    ]
)

new_model.compile(optimizer = keras.optimizers.Adam(learning_rate=1e-2),
       loss = 'sparse_categorical_crossentropy',
       metrics=['accuracy'])

## Fitting Data into Model

Train the model. 
The epochs parameter specifies the number of times the training data should be iterated over during training. In each epoch, the entire training dataset is passed through the model, and the model parameters are updated based on the error between the predicted output and the true output.

Too many `epoch` = Overfitting

Too Less `epoch` = Underfitting

In [26]:
new_model.fit(x_train_scaled,y_train_scaled, epochs = 100)

Epoch 1/100
6/6 [==============================] - 1s 1ms/step - loss: 0.9889 - accuracy: 0.6905
Epoch 2/100
6/6 [==============================] - 0s 3ms/step - loss: 0.4451 - accuracy: 0.8393
Epoch 3/100
6/6 [==============================] - 0s 3ms/step - loss: 0.2485 - accuracy: 0.9464
Epoch 4/100
6/6 [==============================] - 0s 5ms/step - loss: 0.0805 - accuracy: 0.9821
Epoch 5/100
6/6 [==============================] - 0s 4ms/step - loss: 0.1082 - accuracy: 0.9643
Epoch 6/100
6/6 [==============================] - 0s 4ms/step - loss: 0.0363 - accuracy: 0.9881
Epoch 7/100
6/6 [==============================] - 0s 3ms/step - loss: 0.0749 - accuracy: 0.9702
Epoch 8/100
6/6 [==============================] - 0s 4ms/step - loss: 0.0547 - accuracy: 0.9702
Epoch 9/100
6/6 [==============================] - 0s 4ms/step - loss: 0.1881 - accuracy: 0.9405
Epoch 10/100
6/6 [==============================] - 0s 4ms/step - loss: 0.1476 - accuracy: 0.9464
Epoch 11/100
6/6 [===========

## // Evaluate Model & Checking for Overfitting and Underfitting

1st parameter = input data
2nd parameter = target data

Returns list of scalars (if the model has multiple outputs and/or metrics) (in this case loss and accuracy)
The `valueOf_loss` variable will contain the value of the loss function (in this case, `sparse_categorical_crossentropy`) on the testing data. The `valueOf_accuracy` variable will contain the accuracy of the model on the testing data.

If accuracy is low => this could be due to Overfitting

In [27]:
valueOf_loss,valueOf_accuracy = new_model.evaluate(x_test_scaled,y_test_scaled)
print("Loss % =",valueOf_loss*100 , "Accuracy % =",valueOf_accuracy*100)

3/3 [==============================] - 0s 9ms/step - loss: 0.3734 - accuracy: 0.8750
Loss % = 37.341198325157166 Accuracy % = 87.5


## // Campare Actual Stars with Predicted Stars

`model.predict` method is used to predict the class labels for the test dataset `normalized_x_test`. The predicted class probabilities are rounded to the nearest integer using the `numpy.round` function and are assigned to a new variable `z`

In [28]:
# [1,0,0,0,0,0] => Brown Dwarf
# [0,1,0,0,0,0] => Red Dwarf
# [0,0,1,0,0,0] => White Dwarf
# [0,0,0,1,0,0] => Main Sequence
# [0,0,0,0,1,0] => Supergiant
# [0,0,0,0,0,1] => Hypergiant

arr = numpy.array([[1,0,0,0,0,0],[0,1,0,0,0,0],[0,0,1,0,0,0],[0,0,0,1,0,0],[0,0,0,0,1,0],[0,0,0,0,0,1]])

In [29]:
z = numpy.round(new_model.predict(x_test_scaled))

print('_____________________________________________________')
print("    Prediction          Predicted-Class      Actual-Class ")

c1=c2=c3=c4=c5=c6=c7=c8=c9=c10=c11=c12=0  #counter variables

for i in range(0,len(z)):
    if numpy.array_equal(z[i],arr[0]):
        print("{}         :  {} :             {}".format(z[i],0,y_test_scaled[i]))
        c1+=1
    elif numpy.array_equal(z[i],arr[1]):
        print("{}         :  {} :             {}".format(z[i],1,y_test_scaled[i]))
        c2+=1
    elif numpy.array_equal(z[i],arr[2]):
        print("{}         :  {} :             {}".format(z[i],2,y_test_scaled[i]))
        c3+=1  
    elif numpy.array_equal(z[i],arr[3]):
        print("{}         :  {} :             {}".format(z[i],3,y_test_scaled[i]))
        c4+=1 
    elif numpy.array_equal(z[i],arr[4]):
        print("{}         :  {} :             {}".format(z[i],4,y_test_scaled[i]))
        c5+=1
    elif numpy.array_equal(z[i],arr[5]):
        print("{}         :  {} :             {}".format(z[i],5,y_test_scaled[i]))
        c6+=1    

print('_____________________________________________________')
print("Predicted NO. of Brown Dwarfs        =", c1)
print("Predicted NO. of Red Dwarfs          =", c2)
print("Predicted NO. of White Dwarfs        =", c3)
print("Predicted NO. of Main Sequence stars =", c4)
print("Predicted NO. of Supergiants         =", c5)
print("Predicted NO. of Hypergiants         =", c6)
print("Total tested stars                   =", len(z))

m = y_test_scaled

print('_____________________________________________________')

for i in range(0,len(m)):
    if m[i] == 0:
        c7+=1
    elif m[i] == 1 :
        c8+=1 
    elif m[i] == 2 :
        c9+=1 
    elif m[i] == 3 :
        c10+=1 
    elif m[i] == 4 :
        c11+=1 
    elif m[i] == 5 :
        c12+=1     


print("Actual NO. of Brown Dwarfs        =", c7)
print("Actual NO. of Red Dwarfs          =", c8)
print("Actual NO. of White Dwarfs        =", c9)
print("Actual NO. of Main Sequence stars =", c10)
print("Actual NO. of Supergiants         =", c11)
print("Actual NO. of Hypergiants         =", c12)
print("Total tested stars                =", len(x_test_scaled))

print('_____________________________________________________')
print('Accuracy = {}%'.format((valueOf_accuracy*100)))

3/3 [==============================] - 0s 9ms/step
_____________________________________________________
    Prediction          Predicted-Class      Actual-Class 
[0. 0. 0. 0. 1. 0.]         :  4 :             [4.]
[0. 0. 0. 0. 1. 0.]         :  4 :             [4.]
[0. 0. 1. 0. 0. 0.]         :  2 :             [2.]
[0. 0. 0. 0. 0. 1.]         :  5 :             [5.]
[0. 0. 0. 1. 0. 0.]         :  3 :             [4.]
[0. 1. 0. 0. 0. 0.]         :  1 :             [1.]
[0. 0. 0. 0. 0. 1.]         :  5 :             [5.]
[0. 1. 0. 0. 0. 0.]         :  1 :             [1.]
[1. 0. 0. 0. 0. 0.]         :  0 :             [0.]
[1. 0. 0. 0. 0. 0.]         :  0 :             [0.]
[0. 1. 0. 0. 0. 0.]         :  1 :             [1.]
[0. 0. 0. 0. 1. 0.]         :  4 :             [4.]
[0. 0. 0. 0. 0. 1.]         :  5 :             [5.]
[0. 1. 0. 0. 0. 0.]         :  1 :             [0.]
[0. 0. 0. 1. 0. 0.]         :  3 :             [3.]
[0. 0. 0. 0. 1. 0.]         :  4 :             [4.]
[0. 

In [30]:
######   End Of the Notebook . Thanks For Reading .   ########